#!/bin/bash -l 
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:10:00 
#SBATCH -J shun-suffix-tree
#SBATCH -o shun-suffix-tree.%j.out
#SBATCH -e shun-suffix-tree.%j.err

cd ${PWD}
srun -n 1 ./cartesianTree $SCRATCH/striped/nodes-100M.tsv $SCRATCH/striped/shun-output.tsv

